application: blackberry10lp
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /js
  static_dir: js
- url: /[0-9]*
  script: _go_app
- url: /mu.*
  script: _go_app
- url: /.*clicks
  script: _go_app
- url: /.*
  script: _go_app
